#!/usr/bin/env bash

set -e

identifier="com.ninxsoft.mist.helper"

if ! launchctl print "system/$identifier" &> /dev/null ; then
  launchctl bootstrap system "/Library/LaunchDaemons/$identifier.plist"
fi

exit 0
